# -*- coding: utf-8 -*-
"""Dữ liệu nội dung website ANSON JSC – trích từ Hồ sơ năng lực 2026."""

COMPANY = {
    "name": "CÔNG TY CỔ PHẦN AN SƠN",
    "name_title": "Công ty Cổ phần An Sơn",
    "name_en": "AN SON JOINT-STOCK COMPANY",
    "short": "ANSON JSC",
    "domain": "ansonjsc.com.vn",
    "url": "https://ansonjsc.com.vn",
    "address": "Số 448/1 Đường 448, Phường Tăng Nhơn Phú, TP. Hồ Chí Minh",
    "address_short": "448/1 Đường 448, P. Tăng Nhơn Phú, TP.HCM",
    "map_query": "448/1 Đường 448, Phường Tăng Nhơn Phú, Thành phố Hồ Chí Minh",
    "tel1": "028.3730 5647",
    "tel1_raw": "02837305647",
    "tel2": "028.3730 5648",
    "tel2_raw": "02837305648",
    "fax": "028.3730 5648",
    "hotline": "0903 600 205",
    "hotline_raw": "0903600205",
    "email": "congtycpanson@gmail.com",
    "capital": "2.000.000.000 đồng (Hai tỷ đồng)",
    "tax": "0304870975",
    "license": "Số 0304870975 do Sở Kế hoạch và Đầu tư TP. Hồ Chí Minh cấp lần đầu ngày 15/03/2007",
    "founded": "15/03/2007",
    "slogan": "Tiến độ – Chất lượng – Uy tín – Bền vững",
    "ceo": "Ths. Trần Minh Nhật",
    "pdf": "assets/docs/ho-so-nang-luc-anson-2026.pdf",
}

NAV = [
    ("index.html", "Trang chủ"),
    ("gioi-thieu.html", "Giới thiệu"),
    ("nang-luc.html", "Năng lực"),
    ("du-an.html", "Dự án"),
    ("lien-he.html", "Liên hệ"),
]

# 12. Ngành nghề kinh doanh chính (a–j)
FIELDS = [
    "Tư vấn lập dự án đầu tư",
    "Tư vấn thiết kế xây dựng công trình giao thông (cầu, đường bộ)",
    "Tư vấn thẩm tra thiết kế và lập tổng dự toán công trình",
    "Tư vấn đấu thầu",
    "Tư vấn thiết kế quy hoạch đô thị",
    "Khảo sát địa hình, địa chất, thủy văn xây dựng công trình",
    "Tư vấn giám sát thi công xây dựng: giao thông (cầu, đường bộ)",
    "Tư vấn giám sát thi công xây dựng: hạ tầng kỹ thuật",
    "Tư vấn giám sát công tác khảo sát xây dựng",
    "Thi công xây dựng công trình giao thông",
]

# Nhóm dịch vụ hiển thị trang chủ (icon, tiêu đề, mô tả)
SERVICES = [
    ("plan", "Lập dự án đầu tư & quy hoạch",
     "Tư vấn chuẩn bị và lập báo cáo nghiên cứu khả thi (Pre-FS, FS), lập dự án đầu tư, thiết kế quy hoạch đô thị cho các dự án hạ tầng giao thông."),
    ("survey", "Khảo sát địa hình – địa chất – thủy văn",
     "Khảo sát phục vụ thiết kế với thiết bị toàn đạc điện tử TOPCON, kinh vĩ LEICA, thủy bình NIKON/SOKKIA; tư vấn giám sát công tác khảo sát."),
    ("bridge", "Thiết kế công trình giao thông",
     "Thiết kế bản vẽ thi công, lập dự toán cầu – đường bộ từ cấp IV đến cấp I: đường đô thị, cầu dầm BTCT DƯL, cầu vượt sông nhịp lớn."),
    ("check", "Thẩm tra thiết kế & tư vấn đấu thầu",
     "Thẩm tra thiết kế, thẩm tra dự toán – tổng dự toán; lập hồ sơ mời thầu, đánh giá hồ sơ dự thầu cho chủ đầu tư."),
    ("eye", "Tư vấn giám sát thi công",
     "Giám sát thi công công trình giao thông, hạ tầng kỹ thuật và khảo sát xây dựng cho các dự án cao tốc, vành đai, đường đô thị."),
    ("build", "Thi công xây dựng công trình giao thông",
     "Thi công sửa chữa, gia cường, mở rộng cầu (căng cáp DƯL ngoài, vải sợi carbon), kiểm định thử tải cầu, xây mới cầu và đường."),
]

VALUES = [
    ("clock", "Tiến độ", "Tổ chức nhân lực và thiết bị hợp lý, cam kết hoàn thành đúng và vượt tiến độ hợp đồng."),
    ("shield", "Chất lượng", "Tuân thủ quy chuẩn – tiêu chuẩn, kiểm soát chất lượng chặt chẽ ở mọi giai đoạn thực hiện."),
    ("handshake", "Uy tín", "Hơn 18 năm đồng hành cùng các Ban QLDA, Sở GTVT và chủ đầu tư trên cả nước."),
    ("leaf", "Bền vững", "Ứng dụng công nghệ mới, phát triển đội ngũ, hướng tới giá trị lâu dài cho khách hàng và cộng đồng."),
]

STATS = [
    (18, "+", "Năm kinh nghiệm"),
    (50, "+", "Cán bộ, kỹ sư, cộng tác viên"),
    (45, "+", "Hợp đồng đã & đang thực hiện"),
    (120, "+ tỷ", "Tổng giá trị hợp đồng (VNĐ)"),
]

LEADERS = [
    ("Bùi Thị Hiền", "Chủ tịch Hội đồng quản trị", "Thạc sĩ", "BH"),
    ("Trần Minh Nhật", "Tổng Giám đốc", "Thạc sĩ", "TN"),
    ("Đỗ Minh Khánh", "Phó Tổng Giám đốc – Trưởng phòng Khảo sát – Thiết kế", "Thạc sĩ", "ĐK"),
]

# Phòng ban: (tên, phụ trách, [(tên, chức vụ), ...])
DEPARTMENTS = [
    ("Ban Giám đốc và cố vấn", "", [
        ("Ths. Bùi Thị Hiền", "Chủ tịch HĐQT"),
        ("Ths. Trần Minh Nhật", "Tổng Giám đốc"),
        ("Ths. Đỗ Minh Khánh", "Phó Tổng Giám đốc"),
    ]),
    ("Phòng Hành chính – Tổng hợp", "", [
        ("Lê Ngọc Cẩm Vân", "Nhân viên"),
        ("Vi Thùy Dương", "Nhân viên"),
        ("Nguyễn Thị Nga", "Nhân viên"),
    ]),
    ("Phòng Tài chính – Kế toán", "Kế toán trưởng: CN. Nguyễn Thị Kim Dung", [
        ("CN. Nguyễn Thị Kim Dung", "Kế toán trưởng"),
        ("CN. Hồ Trần Thị Thanh Thủy", "Nhân viên"),
        ("CN. Nguyễn Thị Thu", "Cố vấn"),
    ]),
    ("Phòng Khảo sát – Thiết kế", "Trưởng phòng: Ths. Đỗ Minh Khánh · Phó phòng: KS. Nguyễn Hữu Hướng", [
        ("Ths. Đỗ Minh Khánh", "Trưởng phòng"),
        ("KS. Nguyễn Hữu Hướng", "Phó phòng"),
        ("KS. Trịnh Ngọc Hoàng", "Nhân viên"),
        ("KS. Lâm Duy Tài", "Nhân viên"),
        ("KS. Nguyễn Hoàng Tân", "Nhân viên"),
        ("KS. Lã Hà Thẩm Kỳ", "Nhân viên"),
        ("KS. Nguyễn Thị Quỳnh Trâm", "Nhân viên"),
        ("KS. Trần Thị Thanh Huyền", "Nhân viên"),
        ("KS. Võ Quốc Tuấn", "Nhân viên"),
        ("KS. Hồ Thị Oanh", "Nhân viên"),
        ("KS. Nguyễn Sĩ Vinh", "Nhân viên"),
        ("Ths. Trần Thanh Tú", "Cộng tác viên"),
        ("KS. Vũ Hoàng Anh", "Cộng tác viên"),
        ("KS. Phạm Lê Thanh Tú", "Cộng tác viên"),
        ("KTS. Huỳnh Văn Dung", "Cộng tác viên"),
        ("CN. Nguyễn Đăng Khoa", "Cộng tác viên"),
        ("KS. Đỗ Tiến Khoa", "Cộng tác viên"),
        ("KS. Đậu Thiện Lương", "Cộng tác viên"),
        ("Ths. Vũ Trọng Thuật", "Cộng tác viên"),
        ("KS. Phạm Châu Long", "Cộng tác viên"),
        ("KS. Đinh Văn Hạnh", "Cộng tác viên"),
        ("TS. Nguyễn Quang Dũng", "Cộng tác viên"),
        ("KS. Nguyễn Thị Minh", "Cộng tác viên"),
        ("KS. Vũ Minh Tân", "Cộng tác viên"),
    ]),
    ("Phòng Kỹ thuật – Giám sát", "Phụ trách: KS. Trần Duy Tân · KS. Vũ Trường Thi", [
        ("KS. Trần Duy Tân", "Phụ trách"),
        ("KS. Vũ Trường Thi", "Phụ trách"),
        ("KS. Phạm Quốc Tuấn", "Nhân viên"),
        ("KS. Phạm Xuân Bưởi", "Nhân viên"),
        ("KS. Nguyễn Trung Tuyến", "Nhân viên"),
        ("KS. Huỳnh Tấn Thanh", "Nhân viên"),
        ("KS. Đỗ Văn Hiếu", "Nhân viên"),
        ("KS. Huỳnh Quang Tuấn", "Nhân viên"),
        ("KS. Võ Lê Duy Khánh", "Nhân viên"),
        ("Ths. Nguyễn Quý Long", "Nhân viên"),
        ("KS. Hoàng Mạnh Toàn", "Nhân viên"),
        ("KS. Hoàng Bảo Vũ", "Nhân viên"),
        ("KS. Châu Tiếng Tri", "Nhân viên"),
        ("KS. Đoàn Võ Anh Duy", "Nhân viên"),
        ("KS. Nguyễn Hữu Phước Thành", "Nhân viên"),
        ("KS. Trần Sinh", "Nhân viên"),
        ("KS. Đặng Trọng Phúc", "Nhân viên"),
        ("KS. Nguyễn Thành Trung", "Nhân viên"),
    ]),
]

# Sơ đồ tổ chức (theo trang 8 HSNL)
ORG_LEFT = ["Phòng Hành chính", "Phòng Kinh doanh", "Phòng Tài chính – Kế toán", "Phòng Kỹ thuật"]
ORG_LEFT_TEAM = "Đội thi công"
ORG_RIGHT = ["Phòng Khảo sát – Thiết kế", "Phòng Quản lý chất lượng", "Phòng Giám sát"]

EQUIP_OFFICE = [
    ("Máy vi tính", "Bộ", 25),
    ("Máy in từ A4 – A0", "Cái", 1),
    ("Máy in A4", "Cái", 4),
    ("Máy scanner", "Cái", 1),
    ("Máy photocopy", "Cái", 2),
    ("Máy fax", "Cái", 1),
]
EQUIP_SOFTWARE = [
    ("Phần mềm kế toán Việt Nam", "Khóa cứng", 1),
    ("Phần mềm văn phòng điện tử Portaloffice", "Khóa cứng", 1),
    ("Phần mềm khảo sát thiết kế tổng hợp ANDDesign 2008", "Khóa cứng", 1),
    ("Phần mềm tính toán đơn giá dự toán DELTA", "Khóa cứng", 2),
]
EQUIP_SITE = [
    ("Máy hàn", "Cái", 1),
    ("Máy khoan bê tông cầm tay", "Cái", 3),
    ("Máy nén khí PUMA PX-1090", "Cái", 1),
    ("Máy cắt uốn liên hợp Gate GQW-40", "Cái", 2),
    ("Máy toàn đạc điện tử TOPCON", "Cái", 2),
    ("Máy kinh vĩ điện tử LEICA T110 + chân máy + mia", "Cái", 2),
    ("Máy thủy bình NIKON AX-2S + chân máy + mia", "Cái", 2),
    ("Máy đục phá bê tông Maktec MT 875", "Cái", 2),
    ("Máy khoan rút lõi bê tông Ken 6130", "Cái", 2),
    ("Kích căng kéo YDC 250 QX-200", "Bộ", 2),
    ("Máy bơm nước", "Cái", 1),
    ("Máy trộn bê tông + motor 350L-QT", "Bộ", 2),
    ("Máy cắt cầm tay LSTON JSD-1201", "Cái", 2),
    ("Máy hàn điện Hồng Ký 400A", "Cái", 2),
    ("Tời điện ZKCRANE 5 tấn", "Bộ", 1),
    ("Palăng xích kéo tay 3 tấn", "Bộ", 1),
    ("Máy cắt cáp HHYD-50A 12KW", "Bộ", 1),
    ("Máy luồn cáp 20KW", "Bộ", 1),
    ("Máy siêu âm cốt thép Matest C369", "Bộ", 1),
    ("Loa cầm tay", "Cái", 3),
    ("Bộ đàm", "Cái", 3),
    ("Máy thủy bình tự động SOKKIA C32 + chân máy", "Bộ", 1),
]

FIN_YEARS = ["2023", "2024", "2025"]
FINANCE = [
    ("Tổng tài sản", [7681467303, 6266167206, 6686134779]),
    ("Tổng nợ", [5615310928, 4232628769, 4340606230]),
    ("Giá trị tài sản ròng", [2066156375, 2033538437, 2345528549]),
    ("Tổng doanh thu", [13285171327, 6206769494, 15672951851]),
    ("Lợi nhuận sau thuế", [59299149, 26681241, 338671353]),
]

# ---------------- HỢP ĐỒNG ----------------
# (chủ đầu tư, nội dung, giá trị VNĐ, cấp công trình)
CONTRACTS_A = [  # Tư vấn khảo sát, lập DAĐT, TKBVTC, dự toán
    ("CN Công ty Tư vấn Triển khai Công nghệ và Xây dựng Giao thông",
     "Tư vấn khảo sát, lập dự án đầu tư, thiết kế bản vẽ thi công và lập dự toán. Công trình: Xây dựng đường nối từ đường Nguyễn Duy Trinh vào KCN Phú Hữu, Phường Phú Hữu, Quận 9, TP.HCM",
     3569311000, "II"),
    ("Ban QLĐTXD công trình giao thông đô thị Thành phố",
     "Tư vấn chuẩn bị nghiên cứu khả thi (bước Pre-FS) Phát triển giao thông xanh TP.HCM",
     1270000000, "I"),
    ("Ban QLĐTXD công trình giao thông đô thị Thành phố",
     "Tư vấn lập dự án đầu tư xây dựng công trình (bước Nghiên cứu khả thi FS) Phát triển giao thông xanh TP.HCM",
     2290310300, "I"),
    ("Ban QLĐTXD công trình Quận Thủ Đức",
     "Tư vấn lập thiết kế BVTC Nâng cấp, mở rộng đường Trường Thọ, Phường Trường Thọ, Quận Thủ Đức",
     1579764000, "III"),
    ("CN Công ty Tư vấn Triển khai Công nghệ và Xây dựng Giao thông",
     "Cung cấp dịch vụ Giao thông đô thị bền vững hợp nhất (CS4) do Ngân hàng Phát triển Châu Á (ADB) tài trợ",
     4643168000, "I"),
    ("Ban QLDA ĐTXD ngành Giao thông tỉnh Tây Ninh",
     "Tư vấn khảo sát và lập thiết kế bản vẽ thi công – dự toán, công trình: Đường Đất Sét – Bến Củi, Tây Ninh",
     822977000, "IV"),
    ("Ban QLĐTXD công trình Quận 2",
     "Tư vấn khảo sát và lập thiết kế bản vẽ thi công – dự toán, dự án: Xây dựng đường Nguyễn Duy Trinh (đoạn từ cầu Giồng Ông Tố đến cầu Xây Dựng), Quận 2",
     2900000000, "III"),
    ("Ban QLDA ĐTXD tỉnh Bình Dương",
     "Tư vấn lập báo cáo nghiên cứu khả thi dự án: Xây dựng đường và cầu kết nối tỉnh Bình Dương và tỉnh Tây Ninh",
     724893000, "II"),
    ("Ban QLDA ĐTXD tỉnh Bình Dương",
     "Tư vấn khảo sát, lập thiết kế bản vẽ thi công và dự toán dự án: Xây dựng đường và cầu kết nối tỉnh Bình Dương và tỉnh Tây Ninh",
     4449363385, "II"),
    ("Ban QLDA ĐTXD khu vực huyện An Biên",
     "Tư vấn khảo sát, lập báo cáo nghiên cứu khả thi dự án Đường kết nối đê bao ven biển với Cầu Thứ Ba",
     3136139306, "II"),
    ("Ban QLDA ĐTXD công trình giao thông và Nông nghiệp tỉnh An Giang",
     "Tư vấn khảo sát, TKBVTC – dự toán hạng mục công trình chính (phần cầu, đường vào cầu, hệ thống chiếu sáng, bến phà tạm) thuộc dự án Cầu Phú Vĩnh",
     1036100000, "III"),
    ("Ban QLDA ĐTXD các công trình giao thông tỉnh Bình Thuận",
     "Tư vấn khảo sát, lập thiết kế bản vẽ thi công – dự toán và cắm cọc giải phóng mặt bằng công trình (kể cả chi phí dự phòng). Dự án: Nâng cấp, mở rộng đường Bà Tá – Trà Tân",
     1292849000, "III"),
    ("Vườn Quốc gia Phú Quốc",
     "Tư vấn khảo sát địa hình, địa chất, lập thiết kế BVTC và dự toán thuộc Dự án: Xây dựng tuyến đường vành đai bao quanh Vườn Quốc gia Phú Quốc, giai đoạn I",
     2096290219, "IV"),
    ("Ban QLDA và Phát triển quỹ đất huyện Đắk Song",
     "Tư vấn khảo sát, lập TKBVTC – dự toán Dự án Đường ven hồ Đắk R'Lon, thị trấn Đức An đi xã Nam Bình, huyện Đắk Song",
     920238000, "III"),
]

CONTRACTS_B = [  # Tư vấn giám sát khảo sát xây dựng (đã loại trùng lặp)
    ("Ban QLDA ĐTXD các công trình giao thông TP.HCM",
     "Tư vấn giám sát khảo sát giai đoạn lập Báo cáo nghiên cứu khả thi Dự án thành phần 2: Đầu tư xây dựng đường gom dân sinh, cầu vượt ngang đường cao tốc (cao tốc TP. Hồ Chí Minh – Mộc Bài)",
     168830000, "II"),
    ("Ban QLDA ĐTXD các công trình giao thông TP.HCM",
     "Tư vấn giám sát khảo sát giai đoạn lập Báo cáo nghiên cứu khả thi Dự án thành phần 1: Đầu tư xây dựng đường cao tốc TP. Hồ Chí Minh – Mộc Bài (giai đoạn 1) theo phương thức đối tác công tư (hợp đồng BOT)",
     526980000, "Đặc biệt"),
    ("Ban QLĐTXD công trình giao thông đô thị Thành phố",
     "Tư vấn giám sát khảo sát – giai đoạn thiết kế chi tiết Dự án: Phát triển giao thông xanh TP. Hồ Chí Minh",
     431920000, "I"),
    ("Ban QLDA ĐTXD các công trình giao thông TP.HCM",
     "Tư vấn giám sát khảo sát bước lập Báo cáo nghiên cứu khả thi dự án thành phần 1: Xây dựng đường Vành đai 3 đoạn qua TP.HCM (bao gồm kênh Thầy Thuốc)",
     685000000, "I"),
    ("Ban QLĐTXD công trình giao thông đô thị Thành phố",
     "Tư vấn giám sát khảo sát – giai đoạn điều chỉnh nghiên cứu khả thi và thiết kế chi tiết Dự án: Phát triển giao thông xanh TP. Hồ Chí Minh",
     132246000, "I"),
    ("Ban Quản lý Dự án 7",
     "Tư vấn giám sát khảo sát bước thiết kế kỹ thuật, Dự án thành phần đầu tư xây dựng đoạn Vĩnh Hảo – Phan Thiết thuộc Dự án xây dựng một số đoạn đường bộ cao tốc trên tuyến Bắc – Nam phía Đông giai đoạn 2017–2020",
     559237800, "I"),
    ("Ban QLDA ĐTXD các công trình giao thông TP.HCM",
     "Tư vấn giám sát khảo sát bước lập thiết kế kỹ thuật Dự án thành phần 2: Đầu tư xây dựng đường gom dân sinh, cầu vượt ngang đường cao tốc (cao tốc TP. Hồ Chí Minh – Mộc Bài)",
     388711000, "II"),
    ("Ban QLDA ĐTXD các công trình giao thông TP.HCM",
     "Tư vấn giám sát công tác khảo sát bước lập BCNCKT thuộc dự án DATP 2-3: Xây dựng đường cao tốc đoạn từ sông Sài Gòn đến kênh Thầy Cai (bao gồm cầu Phú Thuận qua sông Sài Gòn và cầu Thầy Cai qua kênh Thầy Cai) thuộc dự án đầu tư xây dựng Vành đai 4 TP.HCM",
     214900651, "I"),
    ("Ban QLDA ĐTXD các công trình giao thông TP.HCM",
     "Tư vấn giám sát công tác khảo sát bước lập BCNCKT thuộc dự án DATP 3: Đầu tư xây dựng đường song hành và đường kết nối vào Khu liên hợp đường Vành đai 4 TP. Hồ Chí Minh đoạn từ cầu Thủ Biên – sông Sài Gòn",
     69000000, "I"),
    ("Ban QLDA ĐTXD các công trình giao thông TP.HCM",
     "Tư vấn giám sát khảo sát bước lập BCNCKT thuộc Dự án Đầu tư nút giao thông kết nối đường cao tốc Bến Lức – Long Thành với đường Rừng Sác, huyện Cần Giờ",
     138916714, "Đặc biệt"),
    ("Ban QLDA ĐTXD các công trình giao thông TP.HCM",
     "Tư vấn giám sát khảo sát bước lập TKBVTC thuộc Dự án Đầu tư nút giao thông kết nối đường cao tốc Bến Lức – Long Thành với đường Rừng Sác, huyện Cần Giờ",
     423327868, "Đặc biệt"),
]

CONTRACTS_C = [  # Tư vấn giám sát thi công xây dựng
    ("Ban QLĐTXD công trình giao thông đô thị Thành phố",
     "Tư vấn giám sát thi công kết cấu áo đường, xử lý trồi nhựa mặt đường nhánh C nút giao Cát Lái, Quận 2",
     306805000, "I"),
    ("Ban QLDA ĐTXD Thành phố Thuận An",
     "Tư vấn giám sát thi công xây dựng đường giao thông và hệ thống chiếu sáng, đèn tín hiệu giao thông công trình: Nâng cấp, mở rộng tuyến đường D2, N9 khu dân cư Thuận Giao",
     1014906750, "III"),
    ("Công ty CP Đầu tư và Xây dựng Xa lộ Hà Nội",
     "Tư vấn giám sát thi công Đường song hành phải, đoạn từ cầu Rạch Chiếc đến UBND Quận 9 thuộc dự án mở rộng Xa lộ Hà Nội",
     725000000, "II"),
    ("Ban QLDA ĐTXD công trình giao thông tỉnh Bình Dương",
     "Tư vấn giám sát thi công xây dựng Dự án: Xây dựng cầu bắc qua sông Đồng Nai (cầu Bạch Đằng 2) – Dự án 2: Xây dựng cầu vượt sông Đồng Nai",
     1719582000, "II"),
    ("Sở Giao thông Vận tải tỉnh Kiên Giang",
     "Tư vấn giám sát thi công xây dựng gói thầu số 01 thuộc Dự án: Đầu tư xây dựng công trình đường 3/2 nối dài (đường bộ ven biển tỉnh Kiên Giang – đoạn qua TP. Rạch Giá và huyện Châu Thành)",
     618370200, "II"),
    ("Chi nhánh Công ty TNHH Tư vấn và Xây dựng ĐH GTVT",
     "Gói thầu số 37: Tư vấn giám sát thi công xây lắp công trình (đoạn từ Km43+500 đến cuối Dự án thành phần 1) thuộc Dự án thành phần 1 – Dự án đầu tư xây dựng đường bộ cao tốc Châu Đốc – Cần Thơ – Sóc Trăng (giai đoạn 1)",
     2129344000, "I"),
    ("Sở Xây dựng An Giang",
     "Tư vấn giám sát thi công xây dựng dự án: Đầu tư xây dựng công trình Ngầm hóa hạ tầng kỹ thuật khu vực Dương Đông, TP. Phú Quốc, tỉnh Kiên Giang (nay là đặc khu Phú Quốc, tỉnh An Giang)",
     2483669385, "III"),
]

CONTRACTS_D = [  # Thi công xây dựng công trình
    ("Trung tâm QLDA và TVXD CTGT Bình Thuận",
     "Thi công xây dựng công trình Sửa chữa, nâng cấp Cầu Trần Hưng Đạo, TP. Phan Thiết – Gói thầu số 01: Xây lắp toàn bộ công trình",
     3397402708, "IV"),
    ("Công ty CP VTTB và XDCT 624",
     "Thi công xây dựng công trình: Đường ĐT.782 đoạn từ ngã ba Cây Me đến ngã ba Bàu Đồn – Hạng mục: Cầu Bến Sắn",
     9035828000, "III"),
    ("Công ty TNHH Hoa Mai",
     "Thi công Nâng cấp đường gom KCN Bourbon An Hòa (đoạn đường 787A từ Km0 – Km5) – Hạng mục: Gia tải Cầu Quan",
     4507815000, "IV"),
    ("Sở GTVT Tây Ninh",
     "Thi công bảo trì đường Bourbon",
     5038864000, "IV"),
    ("Ban QLDA Quốc lộ 55 – Sở GTVT Bình Thuận",
     "Thi công xây dựng công trình Sửa chữa, mở rộng cầu Sở Muối, TP. Phan Thiết – Gói thầu số 01: Xây lắp toàn bộ công trình (kể cả đảm bảo an toàn giao thông)",
     4313295267, "IV"),
    ("Sở GTVT Tây Ninh",
     "Thi công công trình: Kiểm định, gia cường nâng tải trọng khai thác Cầu Sài Gòn ĐT.781, huyện Dương Minh Châu, tỉnh Tây Ninh",
     4103441000, "IV"),
    ("Sở GTVT An Giang",
     "Thi công công trình: Sửa chữa, mở rộng mặt cầu Tôn Đức Thắng, TP. Long Xuyên, tỉnh An Giang",
     7128351000, "III"),
    ("Khu Quản lý giao thông đô thị số 3",
     "Thi công công trình: Sửa chữa vừa mặt cầu An Lộc, quận Gò Vấp, TP.HCM",
     9254883000, "IV"),
    ("Sở Giao thông Vận tải tỉnh Bình Dương",
     "Thi công cải tạo, sửa chữa công trình thuộc công trình: Cải tạo, sửa chữa cầu Ông Cộ trên ĐT.744",
     13178121578, "IV"),
    ("Ban Quản lý bảo trì đường bộ Bình Thuận – Sở GTVT Bình Thuận",
     "Thi công xây dựng công trình Sửa chữa cầu Ké, TP. Phan Thiết",
     3884544798, "IV"),
    ("Ban Quản lý bảo trì đường bộ Bình Thuận – Sở GTVT Bình Thuận",
     "Thi công xây dựng công trình Sửa chữa cầu Dục Thanh, TP. Phan Thiết",
     7244447711, "IV"),
    ("Sở GTVT Tây Ninh",
     "Thi công công trình: Kiểm định thử tải cầu, gia cường nâng tải trọng cầu",
     3702716000, "IV"),
    ("Trung tâm Phát triển Hạ tầng Kỹ thuật TP. Thủ Đức",
     "Xây lắp (bao gồm chi phí đảm bảo an toàn giao thông và dự phòng phí) Dự án Xây dựng mới cầu Rạch Môn trên đường 12 (khu dân cư Phú Nhuận), phường Hiệp Bình Chánh",
     9217813363, "IV"),
]

CONTRACT_GROUPS = [
    ("tk", "Tư vấn khảo sát – lập DAĐT – TKBVTC – dự toán", "Thiết kế", CONTRACTS_A),
    ("gsks", "Tư vấn giám sát khảo sát xây dựng", "Giám sát khảo sát", CONTRACTS_B),
    ("gstc", "Tư vấn giám sát thi công xây dựng", "Giám sát thi công", CONTRACTS_C),
    ("tc", "Thi công xây dựng công trình", "Thi công", CONTRACTS_D),
]

# ---------------- DỰ ÁN TIÊU BIỂU ----------------
# (id, nhóm, tên, chủ đầu tư, cấp, [thông số], [ảnh])
PROJECTS = [
    ("phuhuu", "Thiết kế", "Đường nối từ đường Nguyễn Duy Trinh vào KCN Phú Hữu",
     "Công ty Cổ phần Xi măng Hà Tiên 1", "Cấp II",
     ["Chiều dài tuyến 2,626 km; bề rộng mặt cắt ngang 30 m",
      "Kết cấu mặt đường: tấm BTXM M350 dày 24 cm, 2 lớp giấy dầu tạo phẳng, đá dăm gia cố 6% xi măng dày 18 cm, vải địa kỹ thuật phân cách",
      "Nền đường gia cố bằng cọc đất gia cố xi măng",
      "Cống hộp thoát nước 3×3 m; cây xanh; chiếu sáng"],
     ["prj-tk-phuhuu-1.jpg", "prj-tk-phuhuu-2.jpg"]),
    ("truongtho", "Thiết kế", "Nâng cấp, mở rộng đường Trường Thọ, Quận Thủ Đức",
     "Ban QLĐTXD công trình Quận Thủ Đức", "Cấp III",
     ["Chiều dài tuyến 2.220 m; mặt đường rộng 11 m; vỉa hè 4,5 m × 2 bên",
      "Đường đô thị cấp III, tốc độ tính toán 60 km/h",
      "Cầu 3 nhịp × 20 m, chiều dài toàn cầu 60,8 m",
      "Hệ thống cây xanh, chiếu sáng"],
     ["prj-tk-truongtho-1.jpg", "prj-tk-truongtho-2.jpg"]),
    ("gtxanh", "Thiết kế", "Đầu tư Phát triển giao thông xanh TP.HCM (bước FS)",
     "Ban QLĐTXD công trình giao thông đô thị Thành phố", "Cấp I",
     ["Tuyến BRT từ vòng xoay An Lạc đến ga Rạch Chiếc, chiều dài 23 km",
      "Vận tốc thiết kế 60 km/h; bề rộng phần xe chạy 3,5 m",
      "28 trạm dừng; 17 cầu bộ hành"],
     ["prj-tk-gtxanh-1.jpg", "prj-tk-gtxanh-2.jpg"]),
    ("bdtn", "Thiết kế", "Đường và cầu kết nối tỉnh Bình Dương và tỉnh Tây Ninh",
     "Ban QLDA ĐTXD tỉnh Bình Dương", "Cấp II",
     ["Điểm đầu tại nút giao ĐT.744, điểm cuối nối đường Đất Sét – Bến Củi",
      "Chiều dài 800 m; bề rộng 25,5 m; vận tốc thiết kế 80 km/h",
      "Sơ đồ nhịp: 3×39,1 m + 48 m + 72 m + 48 m + 3×39,1 m"],
     ["prj-tk-bdtn-1.jpg", "prj-tk-bdtn-2.jpg"]),
    ("catlai", "Giám sát", "TVGS thi công kết cấu áo đường nhánh C nút giao Cát Lái, Quận 2",
     "Ban QLĐTXD công trình giao thông đô thị Thành phố", "Cấp I",
     ["Vận tốc thiết kế 60 km/h; 2 làn xe cơ giới",
      "Kết cấu mặt đường BTXM; xử lý trồi nhựa mặt đường",
      "Cống hộp thoát nước 2,0×2,0 m; bó vỉa, cây xanh, chiếu sáng"],
     ["prj-gs-catlai-1.jpg", "prj-gs-catlai-2.jpg"]),
    ("xlhn", "Giám sát", "TVGS thi công Đường song hành phải Xa lộ Hà Nội",
     "Công ty CP Đầu tư và Xây dựng Xa lộ Hà Nội", "Cấp II",
     ["Đoạn từ cầu Rạch Chiếc đến UBND Quận 9; chiều dài 2,975 km",
      "Mặt cắt ngang 18 m; mặt đường cấp cao A1; vận tốc thiết kế 60 km/h",
      "Hệ thống thoát nước, bó vỉa, vỉa hè, cây xanh, chiếu sáng"],
     ["prj-gs-xlhn-1.jpg", "prj-gs-xlhn-2.jpg"]),
    ("binhlong", "Giám sát", "TVGS thi công cải tạo hệ thống thoát nước đường Bình Long",
     "Ban QLDA cải tạo kênh Ba Bò", "Cấp I",
     ["Xây mới hệ thống thoát nước tải trọng H30-XB80, khẩu độ D1000, D1200 và cống hộp 2,5×2,5 m; cống ngang D600",
      "Tái lập phui đào và thảm BTN toàn bộ mặt đường",
      "Xây mới bó vỉa, vỉa hè lát gạch Terrazzo"],
     ["prj-gs-binhlong-1.jpg", "prj-gs-binhlong-2.jpg"]),
    ("tranhungdao", "Thi công", "Sửa chữa, nâng cấp cầu Trần Hưng Đạo, TP. Phan Thiết",
     "Trung tâm QLDA và TVXD CTGT Bình Thuận", "Cấp IV",
     ["Chiều dài cầu 138 m (9 nhịp BTCT thường 15,2 m); rộng 19,2 m",
      "Tăng cường dầm chủ bằng vải sợi carbon; bọc cọc trụ cầu",
      "Thảm BTN mặt cầu, đường dẫn; thay mới lan can, lề bộ hành, thoát nước, chiếu sáng, cấp nước"],
     ["prj-tc-tranhungdao-1.jpg", "prj-tc-tranhungdao-2.jpg"]),
    ("somuoi", "Thi công", "Sửa chữa, mở rộng cầu Sở Muối, TP. Phan Thiết",
     "Ban QLDA Quốc lộ 55 – Sở GTVT Bình Thuận", "Cấp IV",
     ["Sửa chữa cầu cũ 2 nhịp 24,7 m (dài 50,2 m, rộng 9,87 m): tăng cường dầm ngang, căng cáp DƯL ngoài",
      "Xây mới 1 cầu kế bên: hệ dầm 18,6 m, rộng 9,87 m",
      "Tổng bề rộng cầu sau mở rộng 19,74 m; tải trọng thiết kế HL93"],
     ["prj-tc-somuoi-1.jpg", "prj-tc-somuoi-2.jpg"]),
    ("tonducthang", "Thi công", "Sửa chữa, mở rộng mặt cầu Tôn Đức Thắng, TP. Long Xuyên",
     "Sở GTVT An Giang", "Cấp III",
     ["Hoạt tải thiết kế H18-XB60, bộ hành 3 kN/m²",
      "Sơ đồ nhịp: 4×24,54 m + 3×33 m + 3×24,54 m",
      "Mở rộng mặt cầu từ 9 m lên 11,5 m; tăng cường dầm ngang; căng cáp DƯL ngoài; thay khe co giãn; cào bóc và thảm mới BTN"],
     ["prj-tc-tonducthang-1.jpg", "prj-tc-tonducthang-2.jpg"]),
    ("ongco", "Thi công", "Cải tạo, sửa chữa cầu Ông Cộ trên ĐT.744",
     "Sở Giao thông Vận tải tỉnh Bình Dương", "Cấp IV",
     ["Hoạt tải thiết kế HL93, bộ hành 3 kN/m²; sơ đồ nhịp 5×24,54 m",
      "Thay mới kết cấu phần trên (dầm chủ, bản mặt cầu, BTN); sửa chữa kết cấu phần dưới (thân, mố, xà mũ trụ)",
      "Bề rộng 8,8 m; thay khe co giãn; cào bóc, thảm mới BTN; cải tạo đường đầu cầu"],
     ["prj-tc-ongco-1.jpg", "prj-tc-ongco-2.jpg"]),
]

HOME_PROJECT_IDS = ["bdtn", "gtxanh", "ongco", "tonducthang", "phuhuu", "xlhn"]

AWARDS = [
    ("award-1.jpg", "Giấy khen Sở GTVT Tây Ninh", "Ghi nhận đóng góp trong công tác xây dựng, bảo trì công trình giao thông tỉnh Tây Ninh."),
    ("award-2.jpg", "Giấy khen UBND tỉnh An Giang", "Ghi nhận thành tích thi công công trình giao thông trên địa bàn tỉnh An Giang."),
    ("award-3.jpg", "Giấy khen Sở GTVT Kiên Giang", "Ghi nhận thành tích trong công tác tư vấn giám sát công trình giao thông tỉnh Kiên Giang."),
]

LEGAL = [
    ("legal-1.jpg", "Giấy chứng nhận đăng ký doanh nghiệp"),
    ("legal-2.jpg", "Chứng chỉ năng lực hoạt động xây dựng (1)"),
    ("legal-3.jpg", "Chứng chỉ năng lực hoạt động xây dựng (2)"),
    ("legal-4.jpg", "Chứng chỉ năng lực hoạt động xây dựng (3)"),
    ("legal-5.jpg", "Chứng chỉ năng lực hoạt động xây dựng (4)"),
    ("legal-6.jpg", "Chứng chỉ năng lực hoạt động xây dựng (5)"),
]

CLIENTS = [
    "Ban QLDA ĐTXD các công trình giao thông TP.HCM",
    "Ban QLĐTXD công trình giao thông đô thị TP.HCM",
    "Ban Quản lý Dự án 7 (Bộ GTVT)",
    "Sở GTVT Tây Ninh",
    "Sở GTVT Bình Thuận",
    "Sở GTVT An Giang",
    "Sở GTVT Kiên Giang",
    "Sở GTVT Bình Dương",
    "Ban QLDA ĐTXD tỉnh Bình Dương",
    "Sở Xây dựng An Giang",
    "Trung tâm Phát triển Hạ tầng Kỹ thuật TP. Thủ Đức",
    "Công ty CP Xi măng Hà Tiên 1",
    "Công ty CP Đầu tư và Xây dựng Xa lộ Hà Nội",
    "Vườn Quốc gia Phú Quốc",
    "Dự án do ADB tài trợ",
]
